server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/leyou?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: mNbDKHnRNYccODsZ0v2tfhvldbtk2YIIe63x1rnvMUq8+D2Rqt93yc2vkI2s6eeXSJFemKyvWq3jsFEj3sUiMA==
    type: com.alibaba.druid.pool.DruidDataSource
    publickey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJjfrAHPfvoUpM6RbWoGTotHcPPCLoMjDxBfCtTefYgLQelvDiBNEtBQ8YctcFkhQ3h/Jm4Ht+uQs3yxSnJultECAwEAAQ==
    druid:
      connect-properties:
        config.decrypt: true
        config.decrypt.key: ${publickey}
      initial-size: 5
      min-idle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,slf4j
      connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
  redis:
    database: 0
    host: 127.0.0.1
    lettuce:
      pool:
        max-active: 80
        max-idle: 80
        max-wait: -1ms
        min-idle: 0
      shutdown-timeout: 100ms
    password: ''
    port: 6379
